server:
  port: 8080

spring:
  redis:
    host: localhost
    port: 6379

jwt:
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvBJrujl1NSaDqIpNkxbB
    NT7h1qiUKZLXdGxp2oWteFPwHscm9DgC6LQf0hJzzccYUKs9nilZ6eoWDRIwtUw2
    cwfzbSiUFXSJNqpa0m7x4gF2Z0S3wH8bkyFW10HKqS1iTL0KWgC44Ns33WOVTyEQ
    7TvWgZnLUC9dbVb15KpfIHU/kw+Y2DuGaX41fWptJ23ochHN+xPOQP8BzKwE270v
    DT4fl+m1k8cR0BBUXLOM8YAq9PUkq52htxRo3swtkSPL6Jt90KhDMWDIk8aLQyeg
    YJZqUu5HOk5Jwbm38DtsKbno7EuySWpSYVdCHUOY1s3UM1OONHAWM4LiNd6wT7hJ
    KQIDAQAB
    -----END PUBLIC KEY-----

logging:
  level:
    root: DEBUG
    com.prashant.api_gateway: TRACE
    org.springframework.cloud.gateway: TRACE
